//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFP
    {
        public AFP()
        {
            this.Descuento = new HashSet<Descuento>();
        }
    
        public int id_AFP { get; set; }
        public string nombre_afp { get; set; }
    
        public virtual ICollection<Descuento> Descuento { get; set; }
    }
}
