//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Stock_RRFF_EMPRESA = new HashSet<Stock_RRFF_EMPRESA>();
            this.Subcategoria = new HashSet<Subcategoria>();
        }
    
        public decimal id_categoria { get; set; }
        public string nombre_categoria { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Stock_RRFF_EMPRESA> Stock_RRFF_EMPRESA { get; set; }
        public virtual ICollection<Subcategoria> Subcategoria { get; set; }
    }
}
