//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public Contrato()
        {
            this.Trabajador_asignado = new HashSet<Trabajador_asignado>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public string id_contrato { get; set; }
        public string nombre_contrato { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public Nullable<decimal> sueldo_base { get; set; }
        public Nullable<decimal> dias_mesuales_req { get; set; }
        public Nullable<decimal> valor_dia { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Trabajador_asignado> Trabajador_asignado { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
