//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public Cotizacion()
        {
            this.Detalle_cotizacion = new HashSet<Detalle_cotizacion>();
        }
    
        public string id_cotizacion { get; set; }
        public string id_proyecto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_proveedor { get; set; }
    
        public virtual ICollection<Detalle_cotizacion> Detalle_cotizacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
