//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Acta_reunion = new HashSet<Acta_reunion>();
            this.Stock_RRFF_EMPRESA = new HashSet<Stock_RRFF_EMPRESA>();
            this.Trabajador_empresa = new HashSet<Trabajador_empresa>();
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public string rol { get; set; }
        public string nombre_empresa { get; set; }
    
        public virtual ICollection<Acta_reunion> Acta_reunion { get; set; }
        public virtual ICollection<Stock_RRFF_EMPRESA> Stock_RRFF_EMPRESA { get; set; }
        public virtual ICollection<Trabajador_empresa> Trabajador_empresa { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
    }
}
