//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public Participante()
        {
            this.Detalle_participacion = new HashSet<Detalle_participacion>();
        }
    
        public string run { get; set; }
        public string nombre { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string responsabilidad { get; set; }
    
        public virtual ICollection<Detalle_participacion> Detalle_participacion { get; set; }
    }
}
