//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Detalle_boleta = new HashSet<Detalle_boleta>();
            this.Detalle_cotizacion = new HashSet<Detalle_cotizacion>();
        }
    
        public string id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
    
        public virtual ICollection<Detalle_boleta> Detalle_boleta { get; set; }
        public virtual ICollection<Detalle_cotizacion> Detalle_cotizacion { get; set; }
    }
}
