//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Comuna = new HashSet<Comuna>();
        }
    
        public decimal id_provincia { get; set; }
        public string nombre_provincia { get; set; }
        public Nullable<decimal> id_region { get; set; }
    
        public virtual ICollection<Comuna> Comuna { get; set; }
        public virtual Region Region { get; set; }
    }
}
