//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Provincia = new HashSet<Provincia>();
        }
    
        public decimal id_region { get; set; }
        public string nombre_region { get; set; }
    
        public virtual ICollection<Provincia> Provincia { get; set; }
    }
}
