//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vialis.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador_empresa
    {
        public Trabajador_empresa()
        {
            this.Descuento = new HashSet<Descuento>();
            this.Trabajador_asignado = new HashSet<Trabajador_asignado>();
        }
    
        public string Persona_run { get; set; }
        public int id_trabajador { get; set; }
        public string oficio_profesion { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<Descuento> Descuento { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Trabajador_asignado> Trabajador_asignado { get; set; }
    }
}
